{% set name = "opencl-clang" %}
{% set version = "10.0.0" %}
{% set llvm_version = version %}

package:
  name: intel-opencl-clang
  version: {{ version }}

source:
  url: https://github.com/intel/opencl-clang/archive/v{{ version }}.tar.gz
  sha256: eb7208ee91bd77c365617424cdf776e33cb2900516430564afabc84892c1937e

build:
  number: 3
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - llvmdev   {{ llvm_version }}
    - llvm      {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - libclang-cpp  {{ llvm_version }}
    - llvm-spirv   {{ llvm_version }}.*
  run:
    - {{ pin_compatible("llvm-spirv", max_pin="x.x.x.x.x.x") }}

test:
  commands:
    - test -f ${PREFIX}/lib/libopencl_clang${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/opencl-clang
  license: NCSA
  license_file: LICENSE
  license_family: BSD
  summary: Common clang is a thin wrapper library around clang. Common clang has OpenCL-oriented API and is capable to compile OpenCL C kernels to SPIR-V modules.

extra:
  recipe-maintainers:
    - isuruf
