{% set name = "opencl-clang" %}
{% set version = "11.0.0" %}
{% set llvm_version = version %}

package:
  name: intel-opencl-clang
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0c0d5fb4bfc85c1c1ae4b441eea223193721ecdd3d9165bcc6f7859d90e5bf66

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - llvmdev   {{ llvm_version }}
    - llvm      {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - libclang-cpp  {{ llvm_version }}
    - llvm-spirv   {{ llvm_version }}
  run:
    - {{ pin_compatible("llvm-spirv", exact=True) }}

test:
  commands:
    - test -f ${PREFIX}/lib/libopencl_clang${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/opencl-clang
  license: NCSA
  license_file: LICENSE
  license_family: BSD
  summary: Common clang is a thin wrapper library around clang. Common clang has OpenCL-oriented API and is capable to compile OpenCL C kernels to SPIR-V modules.

extra:
  recipe-maintainers:
    - isuruf
